In [4]:
from wikidata2df import wikidata2df

In [5]:
query_for_timelines = """
SELECT 
  DISTINCT 
 ?item ?itemLabel
?of ?ofLabel
WHERE {
 ?item p:P31 [ps:P31 wd:Q18340550;
                     pq:P642 wd:Q81068910].  
  
 ?item rdfs:label ?label
       
 OPTIONAL {?item wdt:P1269 ?of}
    SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""

timelines = wikidata2df(query_for_timelines)

In [6]:
query_for_countries = """
SELECT DISTINCT ?item ?itemLabel ?country ?countryLabel WHERE { 
  ?item p:P31 [
              ps:P31 wd:Q3241045;
              pq:P642 wd:Q84263196;
              pq:P3005 ?country
              ].
  values ?type_of_country {wd:Q3624078 wd:Q6256}.
  ?country wdt:P31 ?type_of_country.

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". } 
}
ORDER BY ?country ?dates
"""

countries = wikidata2df(query_for_countries)

In [7]:
timelines

,itemLabel,of,item,ofLabel
0,Timeline of the COVID-19 pandemic in February ...,Q81068910,Q85173796,COVID-19 pandemic
1,Timeline of the COVID-19 pandemic in March 2020,Q81068910,Q87774378,COVID-19 pandemic
2,Timeline of the COVID-19 pandemic,Q84263196,Q83493517,COVID-19
3,Timeline of the COVID-19 pandemic,Q81068910,Q83493517,COVID-19 pandemic
4,timeline of the 2020 coronavirus pandemic in t...,Q83873577,Q87952372,COVID-19 pandemic in the United States
...,...,...,...,...
82,Timeline of the 2020 coronavirus pandemic in T...,Q87473205,Q88616161,2020 COVID-19 pandemic in Turkey
83,Timeline of the COVID-19 pandemic in Japan,Q83872291,Q88650827,COVID-19 pandemic in Japan
84,Timeline of the COVID-19 pandemic in April 2020,Q81068910,Q89016387,COVID-19 pandemic
85,timeline of the 2020 coronavirus pandemic in S...,Q84166704,Q89663058,COVID-19 pandemic in Spain
86,Timeline of the COVID-19 pandemic in India,Q84055514,Q88894143,COVID-19 pandemic in India

In [17]:
for index, row in timelines.iterrows():
    
    timeline_qid = row["item"]
    timeline_label = row["itemLabel"]
    
    for index2, row2 in countries.iterrows():
        
        if row2["itemLabel"].lower() in timeline_label.lower():
            pandemic_qid = row2["item"]
            print(timeline_qid + "|P1269|" + pandemic_qid + "|S887|Q84423633" )

Q97222569|P1269|Q87743866|S887|Q84423633
Q97356055|P1269|Q87186365|S887|Q84423633
Q97357584|P1269|Q87666247|S887|Q84423633
Q94978221|P1269|Q84081576|S887|Q84423633
Q96117882|P1269|Q83873387|S887|Q84423633
Q96409911|P1269|Q84055544|S887|Q84423633
Q96409907|P1269|Q83873580|S887|Q84423633
Q96409908|P1269|Q83873573|S887|Q84423633
Q96409910|P1269|Q84098939|S887|Q84423633
Q96409909|P1269|Q87652000|S887|Q84423633
Q96409906|P1269|Q87768605|S887|Q84423633
Q97382988|P1269|Q87540454|S887|Q84423633
Q98079142|P1269|Q87235137|S887|Q84423633
Q96440383|P1269|Q87250803|S887|Q84423633
Q97704186|P1269|Q86628344|S887|Q84423633
Q105359487|P1269|Q84055514|S887|Q84423633
Q104845051|P1269|Q87186365|S887|Q84423633
Q104880465|P1269|Q87186365|S887|Q84423633
Q106104098|P1269|Q87250803|S887|Q84423633
Q105580995|P1269|Q87666247|S887|Q84423633
Q105605403|P1269|Q87666247|S887|Q84423633
Q105760637|P1269|Q87666247|S887|Q84423633
Q105987348|P1269|Q87666247|S887|Q84423633
Q104635364|P1269|Q87743866|S887|Q84423633
Q104635467|P1269|Q87743866|S887|Q84423633
Q104670356|P1269|Q83873057|S887|Q84423633
Q105070644|P1269|Q83873566|S887|Q84423633
Q105081826|P1269|Q83873548|S887|Q84423633
Q105410018|P1269|Q84104992|S887|Q84423633
Q105393703|P1269|Q83873577|S887|Q84423633
Q106076352|P1269|Q86597695|S887|Q84423633
Q105085571|P1269|Q83873577|S887|Q84423633
Q104855772|P1269|Q84055514|S887|Q84423633
Q104844206|P1269|Q84167106|S887|Q84423633
Q104858887|P1269|Q84167106|S887|Q84423633
Q105085571|P1269|Q83873577|S887|Q84423633
Q88650827|P1269|Q83872291|S887|Q84423633
Q88894143|P1269|Q84055514|S887|Q84423633

In [13]:
"February" in timeline_label

True